### ISSUE TITLE
Raw HTTP data in this repository exposes personal information of Grindr users

### ISSUE THREAD

**Issue by joeycastillo** [SINTEF-9012/grindr-privacy-leaks#2]
Among all the network data captured in the raw-data folder are network requests for thumbnail and full-size images of many unsuspecting Grindr users, as well as the very raw data you're accusing Grindr of mishandling. One JSON listing includes usernames and image URLs for more than 100 users. A dump of another user's profile includes his age, height, HIV status, testing date, sexual position and Instagram handle. A JPEG image of this user's face is also contained within this data dump. 

I don't want to share specific links into the repository, especially for the images that are personally identifying, but [this file](https://github.com/SINTEF-9012/grindr-privacy-leaks/blob/master/raw-data/raw/3046_s.txt) should serve as evidence that there is sensitive information in the repo. Other images in the folder show users' bodies and full faces, or the insides of their homes. The network access log also includes full URLs to the location of these photos in the Grindr CDN, allowing anyone with those URLs to access those images. 

Suggest at minimum scrubbing any raw data and URL references that involve the cdns.grindr.com and grindr.mobi domain names. You should also inform Grindr of any image URLs and profile ID's that were leaked so that they can inform affected users.

**Comment by mikesteele** [comment]
+1

**Comment by yellowiscool** [comment]
Hi. It's a very important issue. The first idea was to publish raw data without any filtering. This exposes public information of a few users indeed. I will filter and remove the data containing content from other users, and send the list to Grindr. Thanks for the report.

**Comment by grinderuser** [comment]
Unfortunately given the severity of the data you've included, I've taken the extraordinary step of contacting SINTEF and Datatilsynet as you appear to be based in Norway and gathered this information there as well.  This is not acceptable.

**Comment by nardev** [comment]
Idiots...

**Comment by yellowiscool** [comment]
Research on social medias has to include social media data from various users. I understand it's unfortunate but the dataset only includes public information as specified by Grindr's terms of use. What's here is not different than what you may see if you install Grindr and use it in Stockholm. Moreover, we think it's more important to raise the issue to the public than not doing anything.

**Comment by grinderuser** [comment]
Grindr's terms of use does not give you permission to gather this information and dump it in GitHub.  No responsible researcher would have done this without ensuring that the data has been scrubbed of PII.

**Comment by yellowiscool** [comment]
You are right.

**Comment by yellowiscool** [comment]
Just to make things clear, this repository only includes data about our test the 7th of February in the center of Stockholm.

So if you weren't using Grindr in February in Stockholm, this repository doesn't contain your public data.

If you are concern that your data is freely available on Github, it's not the case. We did not collect data about Grindr's users and uploaded it to Github. We did an experiment that contains a few public profiles, and decided to not filter the data. We will filter the data.

**Comment by yellowiscool** [comment]
Also, if you are scared that you may find such data on Github, you should probably stop using Grindr because they do share such data to advertisers in clear text.

**Comment by grinderuser** [comment]
It's obviously bad of Grindr to do this, there's no argument there.  But you need to remove the raw data until you have filtered it to ensure that no PII is present and make sure that Grindr has the information needed to inform affected users.

**Comment by yellowiscool** [comment]
Yes, that's the plan.

**Comment by da2x** [comment]
I'm not providing legal advise to anyone in this comment. I only bring this up for discussion.

Did SINTEF obtain and document user consent for this data collection from the people in this data dump? They're EU data subjects and have strong protections under the GDPR. SINTEF would be liable for collecting and distributing extra sensetive personal information under the GDPR. I can't see anything that resembles legitimate interests or grounds for an exception here … .

**Comment by programista18k** [comment]
This is correct. Homosexuality is a sin and god tells us to punish it.
